import { expect, test } from "@playwright/test";

test("fresh temporary database reaches an available pending-publication package", async ({ page, request }, testInfo) => {
  const browserErrors: string[] = [];
  const suffix = `${testInfo.workerIndex}-${testInfo.repeatEachIndex}-${Date.now()}`;
  const productName = `受控露营收纳产品-${suffix}`;
  const contentTitle = `${productName}清单`;
  page.on("console", message => { if (message.type() === "error") browserErrors.push(message.text()); });
  page.on("pageerror", error => browserErrors.push(error.message));
  await page.goto("/radar");
  await page.getByLabel("Expected rows per ranking scope").fill("1");
  await page.getByRole("button", { name: "Start automatic Qianfan collection" }).click();
  await expect(page.getByText(/Collection [0-9a-f-]+ reserved as one batch of 8 scope jobs/)).toBeVisible();
  await expect(page.getByText("Complete: 8/8 scopes succeeded.")).toBeVisible({ timeout: 15_000 });
  await expect(page.getByText(/Selector profile: controlled-qianfan-v1/)).toBeVisible();
  const collectionHeading = page.getByRole("heading", { name: /^Collection [0-9a-f-]+$/ });
  const collectionId = (await collectionHeading.textContent())!.replace("Collection ", "").trim();
  const accountId = `controlled-account-${collectionId}`;
  const accountName = `受控千帆账号-${collectionId}`;
  await page.reload();
  await expect(page.getByRole("link", { name: accountName })).toBeVisible();
  await page.getByRole("link", { name: accountName }).click();
  await expect(page.getByText("Device available: controlled_device_ready")).toBeVisible();
  await page.getByLabel("Expected account notes").fill("1");
  await page.getByRole("button", { name: "Collect account and notes" }).click();
  await expect(page.getByText(/Account collection [0-9a-f-]+ queued/)).toBeVisible();
  await expect(page.getByRole("link", { name: "Open note source" })).toBeVisible({ timeout: 15_000 });
  const collectedNoteEvidence = page.getByLabel(/^account-note:/).first();
  await expect(collectedNoteEvidence).toBeVisible();
  const accountNoteEvidenceId = await collectedNoteEvidence.getAttribute("aria-label");
  expect(accountNoteEvidenceId).toBeTruthy();
  await page.getByLabel("Expected shop products").fill("1");
  await page.getByLabel("Verification evidence directory").fill("fixtures/shop-account");
  await page.getByRole("button", { name: "Queue device collection" }).click();
  const queuedNotice = page.getByText(/Queued job/);
  await expect(queuedNotice).toBeVisible();
  const shopJobId = (await queuedNotice.textContent())!.replace("Queued job ", "").trim();

  await expect.poll(async () => {
    const response = await request.get("http://127.0.0.1:8000/api/v1/jobs");
    const jobs = await response.json() as Array<{ state: string; type: string }>;
    return jobs.find((job: { id?: string; state: string }) => job.id === shopJobId)?.state;
  }).toBe("succeeded");
  await page.reload();
  await expect(page.getByText("1 / 1 verified or collected").last()).toBeVisible();
  const reloadedNoteEvidence = page.getByLabel(accountNoteEvidenceId!);
  await reloadedNoteEvidence.check();
  const deepEvidence = page.getByLabel(/^artifact:/).last();
  await deepEvidence.check();
  const shopEvidenceId = await deepEvidence.getAttribute("aria-label");
  expect(shopEvidenceId).toBeTruthy();
  await page.getByRole("button", { name: "Generate opportunity analysis" }).click();
  await expect(page.getByText(/Opportunity analysis request completed/)).toBeVisible();
  const analyses = await request.get("http://127.0.0.1:8000/api/v1/analyses").then(response => response.json()) as Array<{ account_user_ids: string[]; evidence_ids: string[] }>;
  const collectedAccountAnalysis = analyses.find(item => item.account_user_ids.includes(accountId));
  expect(collectedAccountAnalysis?.evidence_ids).toEqual(expect.arrayContaining([accountNoteEvidenceId!, shopEvidenceId!]));

  await page.goto("/opportunities");
  const opportunityTitle = `受控露营收纳机会-${accountId}-${accountNoteEvidenceId}`;
  await expect(page.getByRole("heading", { name: opportunityTitle })).toBeVisible();
  await page.getByLabel(`Product name for ${opportunityTitle}`).fill(productName);
  await page.getByLabel(`Target user for ${opportunityTitle}`).fill("需要整理露营装备的用户");
  await page.getByRole("button", { name: `Create product for ${opportunityTitle}` }).click();
  await expect(page.getByText(/Created product/)).toBeVisible();

  await page.goto("/content");
  const productRecord = page.getByRole("heading", { name: productName }).locator("..").locator("..");
  await productRecord.getByText("Add managed material").click();
  const materialForm = productRecord.getByText("Add managed material").locator("..");
  await materialForm.getByLabel("Logical filename").fill("source.txt");
  await materialForm.getByLabel("Runtime-relative source path").fill("fixtures/source.txt");
  await materialForm.getByLabel("Media type").fill("text/plain");
  await materialForm.getByRole("button", { name: "Add material" }).click();
  await expect(page.getByText(/Material accepted/)).toBeVisible();
  await page.reload();
  const reloadedProductRecord = page.getByRole("heading", { name: productName }).locator("..").locator("..");
  await reloadedProductRecord.getByText("Add managed material").click();
  const imageForm = reloadedProductRecord.getByText("Add managed material").locator("..");
  await imageForm.getByLabel("Logical filename").fill("cover.png");
  await imageForm.getByLabel("Runtime-relative source path").fill("fixtures/cover.png");
  await imageForm.getByLabel("Media type").fill("image/png");
  await imageForm.getByLabel("Material kind").selectOption("output_image");
  await imageForm.getByRole("button", { name: "Add material" }).click();
  await expect(page.getByText(/Material accepted/)).toBeVisible();
  await page.reload();

  const materials = await request.get("http://127.0.0.1:8000/api/v1/products").then(response => response.json()) as Array<{ materials: Array<{ id: string; kind: string }> }>;
  const createdProduct = (materials as Array<{ id: string; name?: string; materials: Array<{ id: string; kind: string }> }>).find(product => product.name === productName)!;
  const sourceId = createdProduct.materials.find(material => material.kind === "source")!.id;
  const imageId = createdProduct.materials.find(material => material.kind === "output_image")!.id;
  const finalProductRecord = page.getByRole("heading", { name: productName }).locator("..").locator("..");
  await finalProductRecord.getByText("Create model draft").click();
  const draftForm = finalProductRecord.getByText("Create model draft").locator("..");
  await draftForm.getByLabel("Evidence IDs, comma-separated").fill(shopEvidenceId!);
  await draftForm.getByLabel("Source material IDs, comma-separated").fill(sourceId);
  await draftForm.getByLabel("Ordered image material IDs").fill(imageId);
  await draftForm.getByLabel("Research fact").fill("受控证据证明需求存在");
  await draftForm.getByRole("button", { name: "Generate content draft" }).click();
  await expect(page.getByText(/Content draft request completed/)).toBeVisible();
  await page.reload();

  await page.getByLabel(`Review note for ${contentTitle}`).fill("人工核验通过");
  await page.getByLabel(new RegExp(`Visual check for ${imageId}`)).fill("封面清晰且与正文一致");
  await page.getByRole("button", { name: `Approve ${contentTitle}` }).click();
  await expect(page.getByText(/Approval persisted/)).toBeVisible();
  await page.getByRole("button", { name: `Export ${contentTitle}` }).click();
  await expect(page.getByText(/Package available: content-packages\//)).toBeVisible();

  const items = await request.get("http://127.0.0.1:8000/api/v1/content-items").then(response => response.json()) as Array<{ id: string; product_id: string }>;
  const currentItem = items.find(item => item.product_id === createdProduct.id)!;
  const packages = await request.get("http://127.0.0.1:8000/api/v1/content-packages").then(response => response.json()) as Array<{ content_item_id: string; status: string; availability: string }>;
  expect(packages.find(pkg => pkg.content_item_id === currentItem.id)).toEqual(expect.objectContaining({ status: "ready", availability: "available" }));
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath("available-package.png") });
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto("/content");
  await expect(page.getByRole("heading", { name: "Content studio" })).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Workbench" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("mobile-content.png") });
  expect(browserErrors).toEqual([]);
});
